// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIv8f47C-TwZA6xctTGAsQTiD7TzGq8nY',
    appId: '1:805177691565:web:607db9d8b8244e00262524',
    messagingSenderId: '805177691565',
    projectId: 'trend-perfume-push-notificatio',
    authDomain: 'trend-perfume-push-notificatio.firebaseapp.com',
    storageBucket: 'trend-perfume-push-notificatio.firebasestorage.app',
    measurementId: 'G-C207V915HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3FYR6M_RLFNwdhgbeZ_T8oRjXmGTQSMk',
    appId: '1:805177691565:android:b074a547624f9692262524',
    messagingSenderId: '805177691565',
    projectId: 'trend-perfume-push-notificatio',
    storageBucket: 'trend-perfume-push-notificatio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtuBFJSYvRjMAcX8vBEGig-Js2LYVYT2g',
    appId: '1:805177691565:ios:3960d2061e554ca3262524',
    messagingSenderId: '805177691565',
    projectId: 'trend-perfume-push-notificatio',
    storageBucket: 'trend-perfume-push-notificatio.firebasestorage.app',
    iosBundleId: 'com.example.adminDashBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtuBFJSYvRjMAcX8vBEGig-Js2LYVYT2g',
    appId: '1:805177691565:ios:3960d2061e554ca3262524',
    messagingSenderId: '805177691565',
    projectId: 'trend-perfume-push-notificatio',
    storageBucket: 'trend-perfume-push-notificatio.firebasestorage.app',
    iosBundleId: 'com.example.adminDashBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIv8f47C-TwZA6xctTGAsQTiD7TzGq8nY',
    appId: '1:805177691565:web:765311ebbb60474d262524',
    messagingSenderId: '805177691565',
    projectId: 'trend-perfume-push-notificatio',
    authDomain: 'trend-perfume-push-notificatio.firebaseapp.com',
    storageBucket: 'trend-perfume-push-notificatio.firebasestorage.app',
    measurementId: 'G-MWKG7XPFDE',
  );
}
